/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVES_RPC_H_RPCGEN
#define _CLAVES_RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct Coord_sensor {
	int x;
	int y;
};
typedef struct Coord_sensor Coord_sensor;

struct set_value_peticion {
	int key;
	char *value1;
	int N_value2;
	double V_value2[32];
	struct Coord_sensor value3;
};
typedef struct set_value_peticion set_value_peticion;

struct get_value_respuesta {
	int status;
	char *value1;
	int N_value2;
	double V_value2[32];
	struct Coord_sensor value3;
};
typedef struct get_value_respuesta get_value_respuesta;

#define CLAVES 100454255
#define CLAVESVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define destroy_server 1
extern  enum clnt_stat destroy_server_1(int *, CLIENT *);
extern  bool_t destroy_server_1_svc(int *, struct svc_req *);
#define set_value_server 2
extern  enum clnt_stat set_value_server_1(set_value_peticion , int *, CLIENT *);
extern  bool_t set_value_server_1_svc(set_value_peticion , int *, struct svc_req *);
#define get_value_server 3
extern  enum clnt_stat get_value_server_1(int , struct get_value_respuesta *, CLIENT *);
extern  bool_t get_value_server_1_svc(int , struct get_value_respuesta *, struct svc_req *);
#define modify_value_server 4
extern  enum clnt_stat modify_value_server_1(set_value_peticion , int *, CLIENT *);
extern  bool_t modify_value_server_1_svc(set_value_peticion , int *, struct svc_req *);
#define delete_key_server 5
extern  enum clnt_stat delete_key_server_1(int , int *, CLIENT *);
extern  bool_t delete_key_server_1_svc(int , int *, struct svc_req *);
#define exist_server 6
extern  enum clnt_stat exist_server_1(int , int *, CLIENT *);
extern  bool_t exist_server_1_svc(int , int *, struct svc_req *);
extern int claves_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define destroy_server 1
extern  enum clnt_stat destroy_server_1();
extern  bool_t destroy_server_1_svc();
#define set_value_server 2
extern  enum clnt_stat set_value_server_1();
extern  bool_t set_value_server_1_svc();
#define get_value_server 3
extern  enum clnt_stat get_value_server_1();
extern  bool_t get_value_server_1_svc();
#define modify_value_server 4
extern  enum clnt_stat modify_value_server_1();
extern  bool_t modify_value_server_1_svc();
#define delete_key_server 5
extern  enum clnt_stat delete_key_server_1();
extern  bool_t delete_key_server_1_svc();
#define exist_server 6
extern  enum clnt_stat exist_server_1();
extern  bool_t exist_server_1_svc();
extern int claves_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Coord_sensor (XDR *, Coord_sensor*);
extern  bool_t xdr_set_value_peticion (XDR *, set_value_peticion*);
extern  bool_t xdr_get_value_respuesta (XDR *, get_value_respuesta*);

#else /* K&R C */
extern bool_t xdr_Coord_sensor ();
extern bool_t xdr_set_value_peticion ();
extern bool_t xdr_get_value_respuesta ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVES_RPC_H_RPCGEN */
