/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "claves-rpc.h"
#include "claves.h"

bool_t
destroy_1_svc(int *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

    *result = destroy();

    if (*result < 0) {
        retval = FALSE;
    } else {
        retval = TRUE;
    }

	return retval;
}

bool_t
set_value_1_svc(set_value_peticion p, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

    *result = set_value(p.key, p.value1, p.N_value2, p.V_value2, p.value3);

    if (*result < 0) {
        retval = FALSE;
    } else {
        retval = TRUE;
    }

	return retval;
}

bool_t
get_value_1_svc(int key, struct get_value_respuesta *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

    result->status = get_value(key, result->value1, &(result->N_value2), result->V_value2, &(result->value3));

    if (result->status < 0) {
        retval = FALSE;
    } else {
        retval = TRUE;
    }

	return retval;
}

bool_t
modify_value_1_svc(set_value_peticion p, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

    *result = modify_value(p.key, p.value1, p.N_value2, p.V_value2, p.value3);

    if (*result < 0) {
        retval = FALSE;
    } else {
        retval = TRUE;
    }

	return retval;
}

bool_t
delete_key_1_svc(int key, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

    *result = delete_key(key);

    if (*result < 0) {
        retval = FALSE;
    } else {
        retval = TRUE;
    }

	return retval;
}

bool_t
exist_1_svc(int key, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

    *result = exist(key);

    if (*result < 0) {
        retval = FALSE;
    } else {
        retval = TRUE;
    }

	return retval;
}

int
claves_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
